# 24.0 image comes with Debian 12 and pep-0668
FROM qwe1/debdocker:24.0
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends python3 libc6-dev python3-pip gcc git python3-dev python3-setuptools python3-wheel libssl-dev openssh-client
# https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/
ENV ansible_version=2.15.1
ENV ansible_major_version=2.15
ENV ansible_commv=8.1.0
ENV molecule_version=5.1.0
ENV umask=022
ENV PIP_BREAK_SYSTEM_PACKAGES=1
#ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1
# https://peps.python.org/pep-0668
# This can be overriden by passing the --break-system-packages option to pip
RUN rm -f /usr/lib/python3.11/EXTERNALLY-MANAGED && \
    pip3 install --upgrade pip
RUN pip3 install --disable-pip-version-check --break-system-packages ansible==${ansible_commv} ansible-core==${ansible_version} molecule==${molecule_version} molecule-docker docker ansible-lint flake8 yamllint
# python-vagrant pywinrm
RUN apt-get purge --autoremove -y libc6-dev gcc libssl-dev python3-dev python3-wheel && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /root/.cache
# add community.docker:>=3.0.2 + ansible-galaxy collection install -vvv ansible.posix:>=1.4.0
RUN mkdir -p /home/user/.ansible/collections && \
    ansible-galaxy collection install -vvv community.docker -p ~/.ansible/collections && \
    ansible-galaxy collection install -vvv ansible.posix -p ~/.ansible/collections
CMD ["bash"]
